apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql
  labels:
    app: mysql
    tier: database
spec:
  selector: 
    matchLabels:
      app: mysql
  strategy:
    type: Recreate
  template:
    metadata:
      labels: 
        app: mysql
        tier: database
    spec:
      containers:
        - image: mysql
          name: mysql
          env:
           
            - name: MYSQL_HOST
              valueFrom :
                configMapKeyRef :
                  name : mysql-config
                  key :  host

            - name: MYSQL_DATABASE
              valueFrom :
                configMapKeyRef :
                  name : mysql-config
                  key :  db

            - name: MYSQL_USERNAME
              valueFrom :
                secretKeyRef :
                  name : mysql-config
                  key :  user

            - name: MYSQL_ROOT_PASSWORD
              valueFrom :
                secretKeyRef :
                  name : mysql-secrets
                  key :  password

          ports:
            - containerPort: 3306
              name: mysql
          volumeMounts:     
            - name: mysql-persistent-storage
              mountPath: /var/lib/mysql
      volumes:
        - name: mysql-persistent-storage 
          persistentVolumeClaim:
            claimName: mysql-pv-claim
